apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyosk-deployment
  namespace: default
  labels:
    app: kyosk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kyosk
  template:
    metadata:
      labels:
        app: kyosk
    spec:
      containers:
        - name: kyosk
          image: adamsokode/kyosk-config:dev
          ports:
            - containerPort: 8090
          env:
            - name: SERVE_PORT
              value: "8090"

---
# Service Configuration
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kyosk
  name: kyosk-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: kyosk
    run: kyosk-deployment
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: { }
---
# Ingress Configuration
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kyosk-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: "/kyosk-config"
            pathType: Prefix
            backend:
              service:
                name: kyosk-service
                port:
                  number: 80
