apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyosk-deployment
  namespace: default
  labels:
    app: kyosk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kyosk
  template:
    metadata:
      labels:
        app: kyosk
    spec:
      containers:
        - name: kyosk
          image: gazgeek/springboot-helloworld
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kyosk
  name: kyosk-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 32028
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kyosk
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}