version: "3.3"
services:
  mongo:
    image: mongo
    container_name: kyosk-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  kyosk:
    build: .
    ports:
      - 8090:8090
    environment:
      - SERVE_PORT=8090
      - DB_DSN="mongodb://root@example:kyosk-db-service:27017/admin"


