server:
  port: ${SERVE_PORT}

spring:
  data:
    mongo:
      port: 0

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            repository:
              query: debug
